# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ConsultationAppFrontEnd"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/ConsulationAppBackend"
    schedule:
      interval: "weekly"

